import '../models/food_reference.dart';

/// Offline stand‑in when no USDA API key is set (common foods, ~per 100 g edible).
/// Values are rounded approximations for demo / offline use—not a substitute for labelling.
class LocalFoodCatalog {
  LocalFoodCatalog._();

  static const List<FoodReference> _items = [
    // —— Poultry & eggs ——
    FoodReference(
      name: 'Chicken breast, skinless, roasted',
      kcalPer100g: 165,
      proteinPer100g: 31,
      carbsPer100g: 0,
      fatPer100g: 3.6,
      sourceNote: 'local:chicken_breast_roasted',
      imageCategory: 'chicken',
    ),
    FoodReference(
      name: 'Chicken thigh, roasted, skinless',
      kcalPer100g: 176,
      proteinPer100g: 24,
      carbsPer100g: 0,
      fatPer100g: 9,
      sourceNote: 'local:chicken_thigh',
    ),
    FoodReference(
      name: 'Turkey breast, roasted',
      kcalPer100g: 135,
      proteinPer100g: 30,
      carbsPer100g: 0,
      fatPer100g: 1,
      sourceNote: 'local:turkey_breast',
    ),
    FoodReference(
      name: 'Egg, whole, raw',
      kcalPer100g: 143,
      proteinPer100g: 12.6,
      carbsPer100g: 0.7,
      fatPer100g: 9.5,
      sourceNote: 'local:egg_whole',
    ),
    FoodReference(
      name: 'Egg white, raw',
      kcalPer100g: 52,
      proteinPer100g: 10.9,
      carbsPer100g: 0.7,
      fatPer100g: 0.2,
      sourceNote: 'local:egg_white',
    ),

    // —— Red meat & pork ——
    FoodReference(
      name: 'Beef, ground, 93% lean, cooked (crumbles)',
      kcalPer100g: 170,
      proteinPer100g: 26,
      carbsPer100g: 0,
      fatPer100g: 8,
      sourceNote: 'local:beef_lean_ground_cooked',
    ),
    FoodReference(
      name: 'Beef, sirloin steak, lean, trimmed, raw',
      kcalPer100g: 142,
      proteinPer100g: 21,
      carbsPer100g: 0,
      fatPer100g: 6,
      sourceNote: 'local:beef_sirloin_raw',
    ),
    FoodReference(
      name: 'Beef, flank steak, lean, raw',
      kcalPer100g: 165,
      proteinPer100g: 21,
      carbsPer100g: 0,
      fatPer100g: 8,
      sourceNote: 'local:beef_flank',
    ),
    FoodReference(
      name: 'Pork loin, center loin, roasted',
      kcalPer100g: 198,
      proteinPer100g: 28,
      carbsPer100g: 0,
      fatPer100g: 9,
      sourceNote: 'local:pork_loin_roasted',
    ),
    FoodReference(
      name: 'Ham, sliced, extra lean',
      kcalPer100g: 120,
      proteinPer100g: 19,
      carbsPer100g: 1.5,
      fatPer100g: 4,
      sourceNote: 'local:ham_lean',
    ),

    // —— Fish & seafood ——
    FoodReference(
      name: 'Salmon, Atlantic, farmed, raw',
      kcalPer100g: 208,
      proteinPer100g: 20.4,
      carbsPer100g: 0,
      fatPer100g: 13.4,
      sourceNote: 'local:salmon_raw',
    ),
    FoodReference(
      name: 'Tuna, light, canned in water, drained',
      kcalPer100g: 86,
      proteinPer100g: 19.4,
      carbsPer100g: 0,
      fatPer100g: 1,
      sourceNote: 'local:tuna_canned',
    ),
    FoodReference(
      name: 'Shrimp, cooked',
      kcalPer100g: 99,
      proteinPer100g: 24,
      carbsPer100g: 0.2,
      fatPer100g: 0.3,
      sourceNote: 'local:shrimp_cooked',
    ),
    FoodReference(
      name: 'Cod, Atlantic, cooked, dry heat',
      kcalPer100g: 105,
      proteinPer100g: 23,
      carbsPer100g: 0,
      fatPer100g: 0.9,
      sourceNote: 'local:cod_cooked',
    ),

    // —— Plant protein ——
    FoodReference(
      name: 'Tofu, firm, prepared with calcium sulfate',
      kcalPer100g: 144,
      proteinPer100g: 15.8,
      carbsPer100g: 2.8,
      fatPer100g: 8.7,
      sourceNote: 'local:tofu_firm',
    ),
    FoodReference(
      name: 'Tempeh, cooked',
      kcalPer100g: 195,
      proteinPer100g: 20,
      carbsPer100g: 8,
      fatPer100g: 11,
      sourceNote: 'local:tempeh',
    ),

    // —— Dairy ——
    FoodReference(
      name: 'Greek yogurt, plain, nonfat',
      kcalPer100g: 59,
      proteinPer100g: 10.3,
      carbsPer100g: 3.6,
      fatPer100g: 0.4,
      sourceNote: 'local:greek_yogurt_nf',
    ),
    FoodReference(
      name: 'Milk, whole, 3.25% milkfat',
      kcalPer100g: 61,
      proteinPer100g: 3.2,
      carbsPer100g: 4.8,
      fatPer100g: 3.3,
      sourceNote: 'local:milk_whole',
    ),
    FoodReference(
      name: 'Milk, nonfat (skim)',
      kcalPer100g: 35,
      proteinPer100g: 3.4,
      carbsPer100g: 5,
      fatPer100g: 0.1,
      sourceNote: 'local:milk_skim',
    ),
    FoodReference(
      name: 'Cottage cheese, lowfat (2%)',
      kcalPer100g: 86,
      proteinPer100g: 11.7,
      carbsPer100g: 4.8,
      fatPer100g: 2.4,
      sourceNote: 'local:cottage_cheese',
    ),
    FoodReference(
      name: 'Cheddar cheese, sharp',
      kcalPer100g: 403,
      proteinPer100g: 23,
      carbsPer100g: 1.3,
      fatPer100g: 33,
      sourceNote: 'local:cheddar',
    ),
    FoodReference(
      name: 'Mozzarella cheese, part skim',
      kcalPer100g: 254,
      proteinPer100g: 24,
      carbsPer100g: 2.2,
      fatPer100g: 16,
      sourceNote: 'local:mozzarella',
    ),

    // —— Grains & pasta (cooked unless noted) ——
    FoodReference(
      name: 'Rice, white, long-grain, cooked',
      kcalPer100g: 130,
      proteinPer100g: 2.7,
      carbsPer100g: 28,
      fatPer100g: 0.3,
      sourceNote: 'local:white_rice_cooked',
    ),
    FoodReference(
      name: 'Rice, brown, long-grain, cooked',
      kcalPer100g: 130,
      proteinPer100g: 2.7,
      carbsPer100g: 23,
      fatPer100g: 0.3,
      sourceNote: 'local:brown_rice_cooked',
    ),
    FoodReference(
      name: 'Pasta, enriched, cooked (generic)',
      kcalPer100g: 131,
      proteinPer100g: 5,
      carbsPer100g: 25,
      fatPer100g: 1.1,
      sourceNote: 'local:pasta_cooked',
      imageCategory: 'pasta',
    ),
    FoodReference(
      name: 'Spaghetti, enriched, cooked',
      kcalPer100g: 158,
      proteinPer100g: 5.8,
      carbsPer100g: 31,
      fatPer100g: 0.9,
      sourceNote: 'local:spaghetti_cooked',
      imageCategory: 'pasta',
    ),
    FoodReference(
      name: 'Whole wheat pasta, cooked',
      kcalPer100g: 124,
      proteinPer100g: 5.3,
      carbsPer100g: 26,
      fatPer100g: 0.5,
      sourceNote: 'local:pasta_whole_wheat',
    ),
    FoodReference(
      name: 'Bread, white, commercial',
      kcalPer100g: 265,
      proteinPer100g: 9,
      carbsPer100g: 49,
      fatPer100g: 3.2,
      sourceNote: 'local:white_bread',
    ),
    FoodReference(
      name: 'Bread, whole wheat',
      kcalPer100g: 247,
      proteinPer100g: 13,
      carbsPer100g: 41,
      fatPer100g: 4.2,
      sourceNote: 'local:wheat_bread',
    ),
    FoodReference(
      name: 'Bagel, plain (enriched)',
      kcalPer100g: 257,
      proteinPer100g: 10,
      carbsPer100g: 50,
      fatPer100g: 1.7,
      sourceNote: 'local:bagel',
    ),
    FoodReference(
      name: 'Tortilla, flour (10 inch), warmed',
      kcalPer100g: 304,
      proteinPer100g: 8,
      carbsPer100g: 49,
      fatPer100g: 7.5,
      sourceNote: 'local:tortilla_flour',
    ),
    FoodReference(
      name: 'Quinoa, cooked',
      kcalPer100g: 120,
      proteinPer100g: 4.4,
      carbsPer100g: 21,
      fatPer100g: 1.9,
      sourceNote: 'local:quinoa_cooked',
    ),
    FoodReference(
      name: 'Couscous, cooked',
      kcalPer100g: 112,
      proteinPer100g: 3.8,
      carbsPer100g: 23,
      fatPer100g: 0.2,
      sourceNote: 'local:couscous_cooked',
    ),
    FoodReference(
      name: 'Oats, dry (rolled, old fashioned)',
      kcalPer100g: 389,
      proteinPer100g: 16.9,
      carbsPer100g: 66,
      fatPer100g: 6.9,
      sourceNote: 'local:oats_dry',
    ),
    FoodReference(
      name: 'Oatmeal, cooked with water',
      kcalPer100g: 68,
      proteinPer100g: 2.4,
      carbsPer100g: 12,
      fatPer100g: 1.4,
      sourceNote: 'local:oatmeal_cooked',
    ),

    // —— Fruits ——
    FoodReference(
      name: 'Banana, raw',
      kcalPer100g: 89,
      proteinPer100g: 1.1,
      carbsPer100g: 22.8,
      fatPer100g: 0.3,
      sourceNote: 'local:banana',
    ),
    FoodReference(
      name: 'Apple, raw, with skin (mixed varieties)',
      kcalPer100g: 52,
      proteinPer100g: 0.3,
      carbsPer100g: 14,
      fatPer100g: 0.2,
      sourceNote: 'local:apple',
    ),
    FoodReference(
      name: 'Orange, raw (all commercial varieties)',
      kcalPer100g: 47,
      proteinPer100g: 0.9,
      carbsPer100g: 12,
      fatPer100g: 0.1,
      sourceNote: 'local:orange',
    ),
    FoodReference(
      name: 'Blueberries, raw',
      kcalPer100g: 57,
      proteinPer100g: 0.7,
      carbsPer100g: 14.5,
      fatPer100g: 0.3,
      sourceNote: 'local:blueberries',
    ),
    FoodReference(
      name: 'Strawberries, raw',
      kcalPer100g: 32,
      proteinPer100g: 0.7,
      carbsPer100g: 7.7,
      fatPer100g: 0.3,
      sourceNote: 'local:strawberries',
    ),
    FoodReference(
      name: 'Grapes, red or green, raw',
      kcalPer100g: 69,
      proteinPer100g: 0.7,
      carbsPer100g: 18,
      fatPer100g: 0.2,
      sourceNote: 'local:grapes',
    ),
    FoodReference(
      name: 'Watermelon, raw',
      kcalPer100g: 30,
      proteinPer100g: 0.6,
      carbsPer100g: 8,
      fatPer100g: 0.2,
      sourceNote: 'local:watermelon',
    ),
    FoodReference(
      name: 'Avocado, raw',
      kcalPer100g: 160,
      proteinPer100g: 2,
      carbsPer100g: 8.5,
      fatPer100g: 15,
      sourceNote: 'local:avocado',
    ),

    // —— Vegetables ——
    FoodReference(
      name: 'Tomato, red, raw',
      kcalPer100g: 18,
      proteinPer100g: 0.9,
      carbsPer100g: 3.9,
      fatPer100g: 0.2,
      sourceNote: 'local:tomato',
    ),
    FoodReference(
      name: 'Pepper, sweet green bell, raw',
      kcalPer100g: 20,
      proteinPer100g: 0.9,
      carbsPer100g: 4.6,
      fatPer100g: 0.2,
      sourceNote: 'local:green_pepper',
    ),
    FoodReference(
      name: 'Pepper, sweet red bell, raw',
      kcalPer100g: 31,
      proteinPer100g: 1,
      carbsPer100g: 6,
      fatPer100g: 0.3,
      sourceNote: 'local:red_pepper',
    ),
    FoodReference(
      name: 'Onion, yellow, raw',
      kcalPer100g: 40,
      proteinPer100g: 1.1,
      carbsPer100g: 9.3,
      fatPer100g: 0.1,
      sourceNote: 'local:onion',
    ),
    FoodReference(
      name: 'Spinach, raw',
      kcalPer100g: 23,
      proteinPer100g: 2.9,
      carbsPer100g: 3.6,
      fatPer100g: 0.4,
      sourceNote: 'local:spinach_raw',
    ),
    FoodReference(
      name: 'Lettuce, romaine, raw',
      kcalPer100g: 17,
      proteinPer100g: 1.2,
      carbsPer100g: 3.3,
      fatPer100g: 0.3,
      sourceNote: 'local:lettuce_romaine',
    ),
    FoodReference(
      name: 'Carrot, raw',
      kcalPer100g: 41,
      proteinPer100g: 0.9,
      carbsPer100g: 10,
      fatPer100g: 0.2,
      sourceNote: 'local:carrot',
    ),
    FoodReference(
      name: 'Potato, russet, baked, flesh only',
      kcalPer100g: 93,
      proteinPer100g: 2.5,
      carbsPer100g: 21,
      fatPer100g: 0.1,
      sourceNote: 'local:potato_baked',
    ),
    FoodReference(
      name: 'Sweet potato, baked, flesh',
      kcalPer100g: 90,
      proteinPer100g: 2,
      carbsPer100g: 21,
      fatPer100g: 0.2,
      sourceNote: 'local:sweet_potato',
    ),
    FoodReference(
      name: 'Cucumber, with peel, raw',
      kcalPer100g: 15,
      proteinPer100g: 0.7,
      carbsPer100g: 3.6,
      fatPer100g: 0.1,
      sourceNote: 'local:cucumber',
    ),
    FoodReference(
      name: 'Mushrooms, white button, raw',
      kcalPer100g: 22,
      proteinPer100g: 3.1,
      carbsPer100g: 3.3,
      fatPer100g: 0.3,
      sourceNote: 'local:mushrooms',
    ),
    FoodReference(
      name: 'Broccoli, boiled, drained',
      kcalPer100g: 35,
      proteinPer100g: 2.4,
      carbsPer100g: 7.2,
      fatPer100g: 0.4,
      sourceNote: 'local:broccoli_boiled',
    ),
    FoodReference(
      name: 'Cauliflower, raw',
      kcalPer100g: 25,
      proteinPer100g: 1.9,
      carbsPer100g: 5,
      fatPer100g: 0.3,
      sourceNote: 'local:cauliflower',
    ),
    FoodReference(
      name: 'Zucchini, raw',
      kcalPer100g: 17,
      proteinPer100g: 1.2,
      carbsPer100g: 3.1,
      fatPer100g: 0.3,
      sourceNote: 'local:zucchini',
    ),
    FoodReference(
      name: 'Kale, raw',
      kcalPer100g: 35,
      proteinPer100g: 2.9,
      carbsPer100g: 4.4,
      fatPer100g: 1.5,
      sourceNote: 'local:kale',
    ),

    // —— Legumes (cooked) ——
    FoodReference(
      name: 'Black beans, cooked from dry',
      kcalPer100g: 132,
      proteinPer100g: 8.9,
      carbsPer100g: 24,
      fatPer100g: 0.5,
      sourceNote: 'local:black_beans_cooked',
    ),
    FoodReference(
      name: 'Chickpeas (garbanzo), cooked',
      kcalPer100g: 164,
      proteinPer100g: 8.9,
      carbsPer100g: 27,
      fatPer100g: 2.6,
      sourceNote: 'local:chickpeas_cooked',
    ),
    FoodReference(
      name: 'Lentils, mature seeds, cooked',
      kcalPer100g: 116,
      proteinPer100g: 9,
      carbsPer100g: 20,
      fatPer100g: 0.4,
      sourceNote: 'local:lentils_cooked',
    ),
    FoodReference(
      name: 'Kidney beans, red, cooked',
      kcalPer100g: 127,
      proteinPer100g: 8.7,
      carbsPer100g: 23,
      fatPer100g: 0.5,
      sourceNote: 'local:kidney_beans',
    ),

    // —— Nuts, seeds, spreads ——
    FoodReference(
      name: 'Almonds, dry roasted, unsalted',
      kcalPer100g: 607,
      proteinPer100g: 21,
      carbsPer100g: 19,
      fatPer100g: 53,
      sourceNote: 'local:almonds',
    ),
    FoodReference(
      name: 'Peanut butter, smooth',
      kcalPer100g: 588,
      proteinPer100g: 25,
      carbsPer100g: 20,
      fatPer100g: 50,
      sourceNote: 'local:peanut_butter',
    ),
    FoodReference(
      name: 'Walnuts, English, pieces',
      kcalPer100g: 654,
      proteinPer100g: 15,
      carbsPer100g: 14,
      fatPer100g: 65,
      sourceNote: 'local:walnuts',
    ),

    // —— Oils & condiments ——
    FoodReference(
      name: 'Olive oil, extra virgin',
      kcalPer100g: 884,
      proteinPer100g: 0,
      carbsPer100g: 0,
      fatPer100g: 100,
      sourceNote: 'local:olive_oil',
    ),
    FoodReference(
      name: 'Honey',
      kcalPer100g: 304,
      proteinPer100g: 0.3,
      carbsPer100g: 82,
      fatPer100g: 0,
      sourceNote: 'local:honey',
    ),

    // —— Snacks & misc ——
    FoodReference(
      name: 'Dark chocolate, 70–85% cacao',
      kcalPer100g: 598,
      proteinPer100g: 7.8,
      carbsPer100g: 46,
      fatPer100g: 43,
      sourceNote: 'local:dark_chocolate',
    ),
    FoodReference(
      name: 'Granola, homemade style (with nuts)',
      kcalPer100g: 471,
      proteinPer100g: 10,
      carbsPer100g: 64,
      fatPer100g: 20,
      sourceNote: 'local:granola',
    ),
    FoodReference(
      name: 'Protein powder, whey, unflavored (dry)',
      kcalPer100g: 352,
      proteinPer100g: 78,
      carbsPer100g: 8,
      fatPer100g: 4,
      sourceNote: 'local:whey_protein',
    ),
  ];

  static List<FoodReference> search(String query) {
    final raw = query.trim().toLowerCase();
    if (raw.isEmpty) return List.of(_items);
    final tokens =
        raw.split(RegExp(r'\s+')).where((t) => t.length >= 2).toList();
    if (tokens.isEmpty) {
      return _items
          .where((e) => e.name.toLowerCase().contains(raw))
          .toList(growable: false);
    }
    return _items.where((e) {
      final n = e.name.toLowerCase();
      return tokens.every(n.contains);
    }).toList(growable: false);
  }
}
